name = "AbstactMetaArrays"
uuid = "f931004c-b40c-4d45-87f0-83a9870f361d"
authors = ["uriele <menarini.marco@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
